version: "3.8"

services:
  
  # ----------------------------------------
  # MINIO - S3 Compatible Object Storage
  # ----------------------------------------
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9010:9000"  # API port (changed from default 9000 to avoid conflict with Kafdrop)
      - "9011:9090"  # Console port
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9090" /data
    networks:
      - debezium-compose-network
    restart: always
    
  # ----------------------------------------
  # MINIO-CLIENT - For bucket creation
  # ----------------------------------------
  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 admin adminadmin;
      /usr/bin/mc mb myminio/mybucket;
      exit 0;
      "
    networks:
      - debezium-compose-network

networks:
  debezium-compose-network:
    driver: bridge

volumes:
  minio-data:
